#!/usr/bin/with-contenv bash

LD_LIBRARY_PATH=/app/emby exec \
	s6-setuidgid abc /app/emby/EmbyServer \
	-programdata /config \
	-ffdetect /app/emby/ffdetect \
	-ffmpeg /app/emby/ffmpeg \
	-ffprobe /app/emby/ffprobe
