#!/usr/bin/with-contenv bash

# set umask
if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

# env settings
APP_DIR="/app/emby"
export LD_LIBRARY_PATH="${APP_DIR}"
export FONTCONFIG_PATH="${APP_DIR}"/etc/fonts
if [ -d "/lib/x86_64-linux-gnu" ]; then
	export LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri:"${APP_DIR}"/dri
fi
export SSL_CERT_FILE="${APP_DIR}"/etc/ssl/certs/ca-certificates.crt

exec \
	s6-setuidgid abc /app/emby/EmbyServer \
	-programdata /config \
	-ffdetect /app/emby/ffdetect \
	-ffmpeg /app/emby/ffmpeg \
	-ffprobe /app/emby/ffprobe \
	-restartexitcode 3
