#!/usr/bin/with-contenv bash

# Create data if does not exist
mkdir -p /data

# permissions (non-recursive) on config root and folders
chown abc:abc \
	/config \
	/data
if [ -n "$(ls -A /data 2>/dev/null)" ]; then
chown abc:abc \
	/data/*
fi


